# Helm chart definition for Enhanced PA System web portal
# Version: 1.0.0
# Requires Kubernetes >= 1.27.0
# Dependencies: ingress-nginx ^4.7.0, cert-manager ^1.12.0

apiVersion: v2
name: epa-web
description: Helm chart for Enhanced PA System web portal application with high availability, auto-scaling, and security features
type: application
version: 1.0.0
appVersion: 1.0.0
kubeVersion: ">=1.27.0"

maintainers:
  - name: EPA System Team
    email: team@epa-system.com

keywords:
  - healthcare
  - prior-authorization
  - web-portal
  - react
  - typescript
  - cloud-native

dependencies:
  - name: ingress-nginx
    version: ^4.7.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled
  - name: cert-manager
    version: ^1.12.0
    repository: https://charts.jetstack.io
    condition: ingress.tls.enabled

annotations:
  artifacthub.io/changes: "Initial release of EPA System web portal"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "HIPAA-compliant"
  artifacthub.io/recommendations: "production-ready"
  deployment.kubernetes.io/preferred-version: "1.27.0"
  security.cloud-native.io/compliant: "true"
  scaling.kubernetes.io/behavior: "auto-scaling"