version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    ignore:
      - dependency-type: "development"

  # Frontend React dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      mui:
        patterns:
          - "@mui/*"
    ignore:
      - dependency-type: "development"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # AI Service Python dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/ai-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ai-service"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Document Service Python dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/document-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "document-service"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Workflow Service Java dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend/workflow-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "workflow-service"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Integration Service Java dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend/integration-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "integration-service"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"