# Elasticsearch Configuration for Enhanced Prior Authorization System
# Version: 8.9.0
# Purpose: HIPAA-compliant centralized logging and monitoring infrastructure

#----------------------- Cluster Settings -----------------------
cluster:
  name: epa-elasticsearch
  routing:
    allocation:
      disk:
        threshold_enabled: true
        watermark:
          low: "85%"
          high: "90%"

node:
  name: ${NODE_NAME}
  roles: ["master", "data", "ingest"]

discovery.seed_hosts: ["elasticsearch-0", "elasticsearch-1", "elasticsearch-2"]
cluster.initial_master_nodes: ["elasticsearch-0", "elasticsearch-1", "elasticsearch-2"]

#----------------------- Network Settings -----------------------
network.host: "0.0.0.0"
http.port: 9200

#----------------------- Path Settings -----------------------
path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch
  repo: /var/lib/elasticsearch/backup
  audit: /var/log/elasticsearch/audit

#----------------------- Security Settings -----------------------
xpack.security:
  enabled: true
  
  # Transport layer security
  transport.ssl:
    enabled: true
    verification_mode: certificate
    keystore.path: /etc/elasticsearch/certs/elastic-certificates.p12
    truststore.path: /etc/elasticsearch/certs/elastic-certificates.p12
  
  # HTTP layer security
  http.ssl:
    enabled: true
    keystore.path: /etc/elasticsearch/certs/elastic-certificates.p12
  
  # Audit logging
  audit:
    enabled: true
    logfile.events.include: 
      - authentication_success
      - authentication_failure
      - access_denied
      - connection_denied
  
  # Authentication realms
  authc:
    realms:
      native:
        type: native
        order: 0
      file:
        type: file
        order: 1
      ldap:
        type: ldap
        order: 2

#----------------------- Monitoring Settings -----------------------
xpack.monitoring:
  enabled: true
  collection:
    enabled: true
    interval: 30s
  elasticsearch.collection.enabled: true
  history.duration: 7d

#----------------------- Index Settings -----------------------
# Workflow Service Logs
action.auto_create_index: true
index.workflow-service-logs:
  number_of_shards: 3
  number_of_replicas: 2
  refresh_interval: 10s
  lifecycle:
    name: epa-logs-policy
    rollover_alias: epa-logs-workflow
  routing.allocation.total_shards_per_node: 100

# Document Service Logs
index.document-service-logs:
  number_of_shards: 3
  number_of_replicas: 2
  refresh_interval: 10s
  lifecycle:
    name: epa-logs-policy
    rollover_alias: epa-logs-document
  routing.allocation.total_shards_per_node: 100

# AI Service Logs
index.ai-service-logs:
  number_of_shards: 3
  number_of_replicas: 2
  refresh_interval: 10s
  lifecycle:
    name: epa-logs-policy
    rollover_alias: epa-logs-ai
  routing.allocation.total_shards_per_node: 100

# Security Audit Logs
index.security-audit-logs:
  number_of_shards: 3
  number_of_replicas: 2
  refresh_interval: 5s
  lifecycle:
    name: epa-audit-policy
    rollover_alias: epa-security-audit
  routing.allocation.total_shards_per_node: 50

#----------------------- Performance Settings -----------------------
bootstrap.memory_lock: true
indices:
  memory:
    index_buffer_size: "30%"
  queries.cache.size: "5%"
  fielddata.cache.size: "20%"
  recovery:
    max_bytes_per_sec: 100mb
    max_concurrent_file_chunks: 5

thread_pool:
  write.size: 32
  search.size: 16

search:
  max_buckets: 100000
  max_keep_alive: 24h

#----------------------- Security Policies -----------------------
# Encryption Configuration
security.encryption:
  protocol: "TLS 1.3"
  cipher_suites:
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256

# Authentication Settings
security.authentication:
  session_timeout: 8h
  max_failed_attempts: 5

# Role-based Authorization
security.authorization:
  roles:
    - superuser
    - kibana_admin
    - logstash_writer
    - monitoring_user
    - auditor
    - healthcare_viewer