# Enhanced Prior Authorization System - Workflow Service Helm Chart
# Version: 1.0.0
# Production-grade Helm chart for enterprise healthcare deployment

apiVersion: v2
name: workflow-service
description: Production-grade Helm chart for Enhanced Prior Authorization System Workflow Service, providing automated processing, clinical criteria matching, and multi-stakeholder communication capabilities
type: application
version: 1.0.0
appVersion: 1.0.0

# Keywords for chart discovery and categorization
keywords:
  - workflow
  - authorization
  - healthcare
  - epa
  - prior-authorization
  - clinical-workflow
  - hipaa-compliant

# Chart maintainers
maintainers:
  - name: EPA Platform Team
    email: platform-team@epa.healthcare

# Chart dependencies
dependencies:
  - name: postgresql
    version: 12.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache

# Helm template engine
engine: gotpl

# Kubernetes version requirement
kubeVersion: ">=1.24.0-0"

# Additional metadata
annotations:
  artifacthub.io/changes: "Initial production release"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"