# Kubernetes ServiceAccount configurations for Enhanced Prior Authorization System
# Version: 1.0.0
# Kubernetes API Version: v1.27+
# Purpose: Define service-specific identities with enhanced security controls

apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: api-gateway
    security.epa.io/tier: frontend
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "24h"
    security.epa.io/audit-level: "high"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "api-gateway-network-policy"
automountServiceAccountToken: true
secrets:
  - name: api-gateway-tls-cert
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: auth-service
    security.epa.io/tier: security
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "12h"
    security.epa.io/audit-level: "critical"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "auth-service-network-policy"
automountServiceAccountToken: true
secrets:
  - name: auth-service-keys
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-service-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: workflow-service
    security.epa.io/tier: backend
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "24h"
    security.epa.io/audit-level: "high"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "workflow-service-network-policy"
automountServiceAccountToken: true
secrets:
  - name: workflow-service-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: document-service-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: document-service
    security.epa.io/tier: backend
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "24h"
    security.epa.io/audit-level: "critical"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "document-service-network-policy"
automountServiceAccountToken: true
secrets:
  - name: document-service-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: ai-service
    security.epa.io/tier: backend
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "24h"
    security.epa.io/audit-level: "high"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "ai-service-network-policy"
automountServiceAccountToken: true
secrets:
  - name: ai-service-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-service-sa
  namespace: epa-system
  labels:
    app.kubernetes.io/part-of: epa-system
    app.kubernetes.io/component: integration-service
    security.epa.io/tier: backend
    compliance.epa.io/hipaa: "true"
  annotations:
    security.epa.io/auto-rotate: "true"
    security.epa.io/token-ttl: "24h"
    security.epa.io/audit-level: "critical"
    security.epa.io/last-rotation: ""  # Automatically updated by rotation controller
    security.epa.io/compliance-validated: "true"
    security.epa.io/network-policy: "integration-service-network-policy"
automountServiceAccountToken: true
secrets:
  - name: integration-service-secrets