apiVersion: v1
kind: Secret
metadata:
  name: epa-system-secrets
  namespace: epa
  labels:
    app: epa-system
    environment: production
    version: "1.0.0"
  annotations:
    encryption.aws.com/kms-key: "arn:aws:kms:region:account:key/key-id"  # KMS key for envelope encryption
    vault.hashicorp.com/agent-inject: "true"  # Vault integration for secret rotation
    hipaa.compliance/audit-enabled: "true"  # HIPAA compliance tracking
    backup.kubernetes.io/enabled: "true"  # Automated backup
    rotation.kubernetes.io/period: "30d"  # 30-day rotation period
type: Opaque
stringData:
  # Auth Service Secrets - OAuth 2.0 + OIDC credentials
  auth-service.yaml: |
    AUTH0_DOMAIN: "your-tenant.auth0.com"
    AUTH0_CLIENT_ID: "auth0-client-id"
    AUTH0_CLIENT_SECRET: "auth0-client-secret"
    AUTH0_AUDIENCE: "https://api.epa-system.com"
    JWT_SECRET_KEY: "jwt-signing-key"
    ROTATION_KEY: "rotation-encryption-key"
    AUDIT_ENCRYPTION_KEY: "audit-log-encryption-key"
    BACKUP_ENCRYPTION_KEY: "backup-encryption-key"

  # Workflow Service Secrets - Database and encryption keys
  workflow-service.yaml: |
    DB_USER: "workflow_service"
    DB_PASSWORD: "secure-database-password"
    DB_HOST: "postgresql.epa.svc.cluster.local"
    DB_PORT: "5432"
    DB_NAME: "epa_workflow"
    REDIS_PASSWORD: "redis-password"
    ENCRYPTION_KEY: "data-encryption-key"
    FIELD_ENCRYPTION_KEY: "field-level-encryption-key"
    AUDIT_KEY: "audit-trail-key"
    BACKUP_KEY: "backup-encryption-key"
    SSL_CERT_PATH: "/certs/workflow-service.crt"
    SSL_KEY_PATH: "/certs/workflow-service.key"
    SSL_ROOT_CERT_PATH: "/certs/ca.crt"

  # Document Service Secrets - Storage and processing credentials
  document-service.yaml: |
    MONGODB_URI: "mongodb+srv://document_service:password@mongodb.epa.svc.cluster.local/epa_documents?retryWrites=true&w=majority"
    AWS_ACCESS_KEY_ID: "aws-access-key"
    AWS_SECRET_ACCESS_KEY: "aws-secret-key"
    STORAGE_ENCRYPTION_KEY: "s3-encryption-key"
    DOCUMENT_ENCRYPTION_KEY: "document-encryption-key"
    AUDIT_ENCRYPTION_KEY: "audit-log-encryption-key"
    BACKUP_KEY: "backup-encryption-key"

  # AI Service Secrets - Model and API credentials
  ai-service.yaml: |
    OPENAI_API_KEY: "openai-api-key"
    MODEL_ENCRYPTION_KEY: "model-encryption-key"
    GPT_SERVICE_KEY: "gpt-service-key"
    FIELD_ENCRYPTION_KEY: "field-level-encryption-key"
    AUDIT_KEY: "audit-trail-key"
    BACKUP_KEY: "backup-encryption-key"

  # Integration Service Secrets - External system credentials
  integration-service.yaml: |
    EHR_API_KEY: "ehr-system-api-key"
    PHARMACY_API_KEY: "pharmacy-system-api-key"
    INSURANCE_API_KEY: "insurance-system-api-key"
    INTEGRATION_ENCRYPTION_KEY: "integration-encryption-key"
    FIELD_ENCRYPTION_KEY: "field-level-encryption-key"
    AUDIT_KEY: "audit-trail-key"
    BACKUP_KEY: "backup-encryption-key"

  # Monitoring and Alerting Secrets
  monitoring.yaml: |
    ALERT_API_KEY: "alert-system-api-key"
    MONITORING_ENCRYPTION_KEY: "monitoring-encryption-key"
    AUDIT_TRAIL_KEY: "audit-system-key"
    BACKUP_KEY: "backup-encryption-key"