# Helm Chart for Enhanced Prior Authorization System AI Service
# Version: 1.0.0
# Dependencies: pytorch/pytorch:2.0, helm-charts/common:1.x.x

apiVersion: v2
name: ai-service
description: Enhanced Prior Authorization System AI Service for Gen AI processing and clinical criteria matching with GPU acceleration
type: application
version: 1.0.0
appVersion: "1.0.0"

# Kubernetes version requirements
kubeVersion: ">=1.27.0-0"

# Chart keywords for search and categorization
keywords:
  - ai
  - machine-learning
  - healthcare
  - prior-authorization
  - gpu-enabled
  - clinical-nlp
  - document-analysis

# Chart maintainers
maintainers:
  - name: EPA System Team
    email: team@epasystem.com

# Chart dependencies
dependencies:
  - name: common
    version: 1.x.x
    repository: file://../common
    # Common chart provides shared utilities and standardized deployment patterns

# Chart annotations for metadata and capabilities
annotations:
  category: AI/ML
  licenses: MIT
  artifacthub.io/operator: "true"
  artifacthub.io/prerelease: "false"
  healthcare.hipaa/compliant: "true"
  ai.gpu/required: "true"
  monitoring.prometheus/scrape: "true"
  backup.velero/included: "true"

# Home URL and documentation
home: https://epasystem.com/ai-service
sources:
  - https://github.com/epasystem/ai-service

# Additional metadata
icon: https://epasystem.com/icons/ai-service.png
deprecated: false

# System requirements
requirements:
  kubernetes: ">=1.27.0-0"
  helm: ">=3.12.0"
  gpu: "NVIDIA Tesla T4 or better"
  memory: "16Gi minimum"
  cpu: "8 cores minimum"
  storage:
    model: "100Gi SSD minimum"
    cache: "50Gi SSD minimum"
  network:
    bandwidth: "10Gbps minimum"
    latency: "<10ms"