# Grafana Data Sources Configuration v9.5.0
# Enhanced Prior Authorization System Monitoring Configuration

apiVersion: 1

# Data Sources Configuration
datasources:
  # Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-server:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      httpHeaderValue1: ${PROM_ORG_ID}

  # Elasticsearch Data Source
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: epa-logs-*
    isDefault: false
    version: 1
    editable: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.9.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
      interval: Daily
      sslVerify: true
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      basicAuth: true
      basicAuthUser: ${ELASTICSEARCH_USER}
      basicAuthPassword: ${ELASTICSEARCH_PASSWORD}
      tlsCACert: ${ES_CA_CERT}
      tlsClientCert: ${ES_CLIENT_CERT}
      tlsClientKey: ${ES_CLIENT_KEY}