apiVersion: v2
name: document-service
description: A Helm chart for the Enhanced Prior Authorization System Document Service
type: application
version: 1.0.0
appVersion: 1.0.0

# Keywords for chart discovery and categorization
keywords:
  - document-service
  - healthcare
  - prior-authorization
  - document-processing
  - gpu-enabled
  - fastapi

# Chart maintainer information
maintainers:
  - name: EPA System Team
    email: team@epasystem.com

# Chart dependencies
dependencies:
  - name: mongodb
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

# Chart engine
engine: gotpl

# Project metadata
home: https://github.com/epasystem/document-service
icon: https://epasystem.com/icons/document-service.png

# Kubernetes version requirement
kubeVersion: ">=1.24.0-0"

# Additional annotations for the chart
annotations:
  gpu.support: enabled
  scaling.type: vertical
  resource.cpu: "4"
  resource.memory: 8Gi